name: SENTIMENT ANALYSIS CICD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
   Continuous-Integration:
      name: Doing the Continuous Integration
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Set Up Python
           uses: actions/setup-python@v4
           with:
              python-version: "3.11" 

         - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }} 

         - name: Build and Push Docker Images Using Docker Compose
          
           run: |
              docker compose build
              docker tag anuragraj03/sentiment_repo_cicd/sentiment_api:latest anuragraj03/sentiment_repo_cicd:sentiment_api
              docker tag anuragraj03/sentiment_repo_cicd/monitoring_service:latest anuragraj03/sentiment_repo_cicd:monitoring_service
              docker tag anuragraj03/sentiment_repo_cicd/streamlit_app:latest anuragraj03/sentiment_repo_cicd:streamlit_app
              docker push anuragraj03/sentiment_repo_cicd:sentiment_api
              docker push anuragraj03/sentiment_repo_cicd:monitoring_service
              docker push anuragraj03/sentiment_repo_cicd:streamlit_app


         
             
             
