name: SENTIMENT ANALYSIS CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
   Contious-Integration:
      name: Doing the continous Integration
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Set Up Python
           uses: actions/setup-python@v4
           with:
              python-version: "3.11" 

         - name: Log in to Docker hub
           uses: docker/login-action@v2
           with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}} 

         - name: Build and Push Docker Images
           run: |
             docker build -t anuragraj03/sentiment_api:latest ./api
             docker push anuragraj03/sentiment_api:latest

             docker build -t anuragraj03/streamlit_app:latest ./streamlit_app
             docker push anuragraj03/streamlit_app:latest

             docker build -t anuragraj03/monitoring_service:latest ./monitoring
             docker push anuragraj03/monitoring_service:latest


       


         
